version: "3"
services:
  front-app:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /my-app/node_modules
      - .:/my-app
  front-app-prod:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
  test-front-app:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /my-app/node_modules
      - .:/my-app
    command: ["npm", "run", "test"]
