FROM node:20 as builder

WORKDIR /my-app

COPY package.json  package-lock.json ./

RUN npm ci 

COPY  src ./src
COPY  public ./public
COPY  nginx.conf ./

RUN npm run build

FROM nginx

COPY --from=builder /my-app/build /usr/share/nginx/html
# COPY --from=builder /my-app/nginx.conf /etc/nginx/conf.d/default.conf

# CMD ["nginx", "-g", "daemon off;"]


